### ISSUE TITLE
feature: cross-compatibility

### ISSUE THREAD

**Issue by TrizekYT** [Vexcited/lpadder#7]
If we had the option to possibly plug in our launchpads to our phones like Unipad, maybe we could add the ability to work with people that are on PC while you're on the phone or another device.

**Comment by Vexcited** [comment]
lpadder is already cross-compatible, thanks to PWA, and I'll make sure to keep this compatibility across the devices.

I already tested to plug a Launchpad on my phone to test lpadder and it successfully worked like it would on a desktop.
